const authActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_REQUEST_SUCCESS: 'REGISTER_REQUEST_SUCCESS',
  REGISTER_REQUEST_FAIL: 'REGISTER_REQUEST_FAIL',
  REQUEST_USER: 'REQUEST_USER',
  REQUEST_USER_SUCCESS: 'REQUEST_USER_SUCCESS',
  REQUEST_USER_FAIL: 'REQUEST_USER_FAIL',
  CLEAR_ERROR: 'CLEAR_ERROR',
}

export default authActionTypes
